// ── RPC argument helper ──────────────────────────────────────────────────────
// Postgres RPC "Args" types (generated by Supabase) mark optional parameters
// as `key?: T` — never `key?: T | undefined`. Under this project's
// exactOptionalPropertyTypes: true, passing `{ key: undefined }` does NOT
// satisfy `key?: T`: the key must be entirely absent from the object, not
// merely undefined-valued. Service functions build RPC payloads from
// optional input fields (`input.title ?? undefined`), which produces exactly
// that forbidden shape.
//
// pruneRpcArgs() strips null/undefined-valued keys before the call, so the
// object passed to `db.rpc(...)` only ever contains keys PostgREST should
// actually send. The return type keeps keys whose source type never included
// `undefined` as required (so genuinely required RPC params, e.g. org_id,
// still type-check as required at the call site) and makes only the
// undefined-capable keys optional — matching the generated Args shape
// key-for-key instead of loosening every field.

type PruneNullish<T> =
  { [K in keyof T as undefined extends T[K] ? never : K]: T[K] } &
  { [K in keyof T as undefined extends T[K] ? K : never]?: Exclude<T[K], null | undefined> }

export function pruneRpcArgs<T extends Record<string, unknown>>(args: T): PruneNullish<T> {
  const result: Record<string, unknown> = {}
  for (const key of Object.keys(args)) {
    const value = args[key]
    if (value !== null && value !== undefined) {
      result[key] = value
    }
  }
  return result as PruneNullish<T>
}
