// Pure rules for invoice reminder emails -- no network, no Deno APIs -- so the
// "who gets an email today" decision can be tested on its own.

export interface ReminderSettings {
  days_before:  number     // 0 = no "coming due" reminder
  on_due:       boolean
  overdue_days: number[]   // days after the due date, e.g. [3, 7, 14]
}

export type ReminderKind = 'before_due' | 'on_due' | 'overdue'

export interface ReminderChoice {
  kind:       ReminderKind
  day_offset: number       // days_before / 0 / days overdue -- the log's dedupe key
}

// A reminder is due on its day, and still due for WINDOW_DAYS after it, so a
// missed or delayed daily run does not skip it. The window is deliberately
// short: turning reminders on must not flood clients about old invoices.
export const WINDOW_DAYS = 2

const MS_PER_DAY = 86_400_000

/** Calendar date (YYYY-MM-DD) of `now` in the given IANA time zone. */
export function localDate(now: Date, timeZone = 'America/New_York'): string {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone, year: 'numeric', month: '2-digit', day: '2-digit',
  }).formatToParts(now)
  const get = (t: string) => parts.find(p => p.type === t)!.value
  return `${get('year')}-${get('month')}-${get('day')}`
}

/** Whole days from `due` to `today` (both YYYY-MM-DD). Positive = overdue. */
export function daysPastDue(due: string, today: string): number {
  const d = Date.parse(`${due.slice(0, 10)}T00:00:00Z`)
  const t = Date.parse(`${today.slice(0, 10)}T00:00:00Z`)
  return Math.round((t - d) / MS_PER_DAY)
}

/**
 * The one reminder to send for an invoice today, or null.
 * `alreadySent` holds "kind:day_offset" keys from the log. Among the reminders
 * whose window contains today, the latest milestone wins, so a client is never
 * sent two emails for the same invoice on the same run.
 */
export function pickReminder(
  pastDue: number,
  s: ReminderSettings,
  alreadySent: ReadonlySet<string>,
): ReminderChoice | null {
  const candidates: Array<ReminderChoice & { at: number }> = []
  if (s.days_before > 0) {
    candidates.push({ kind: 'before_due', day_offset: s.days_before, at: -s.days_before })
  }
  if (s.on_due) candidates.push({ kind: 'on_due', day_offset: 0, at: 0 })
  for (const d of s.overdue_days) {
    candidates.push({ kind: 'overdue', day_offset: d, at: d })
  }

  const live = candidates
    .filter(c => pastDue >= c.at && pastDue <= c.at + WINDOW_DAYS)
    .filter(c => !alreadySent.has(`${c.kind}:${c.day_offset}`))
    .sort((a, b) => b.at - a.at)
  const best = live[0]
  return best ? { kind: best.kind, day_offset: best.day_offset } : null
}

export function reminderSubject(
  invoiceNumber: string, firmName: string, kind: ReminderKind, pastDue: number,
): string {
  if (kind === 'before_due') {
    const n = -pastDue
    return `Reminder: invoice ${invoiceNumber} is due ${n <= 0 ? 'today' : n === 1 ? 'tomorrow' : `in ${n} days`}`
  }
  if (kind === 'on_due') return `Invoice ${invoiceNumber} is due today`
  return `Overdue: invoice ${invoiceNumber} is ${pastDue} day${pastDue === 1 ? '' : 's'} past due`
}

export function reminderLead(kind: ReminderKind, pastDue: number, firmName: string): string {
  if (kind === 'before_due') {
    const n = -pastDue
    return `This is a friendly reminder from ${firmName} that the invoice below is due ${n <= 0 ? 'today' : n === 1 ? 'tomorrow' : `in ${n} days`}.`
  }
  if (kind === 'on_due') return `This is a friendly reminder from ${firmName} that the invoice below is due today.`
  return `${firmName} has not yet received payment for the invoice below, which is ${pastDue} day${pastDue === 1 ? '' : 's'} past due.`
}

/**
 * Was this invoice created already sent -- i.e. generated by a recurring
 * schedule with auto-send on? A draft that a person sends by hand gets
 * `sent_at` long after `created_at`, so it is not mistaken for one.
 */
export function wasAutoSent(createdAt: string, sentAt: string | null): boolean {
  if (!sentAt) return false
  return Math.abs(Date.parse(sentAt) - Date.parse(createdAt)) < 2 * 60_000
}
