-- Immutable sales-tax record per issued invoice.
-- Applied 2026-09-26 as migrations `invoice_tax_snapshots` and
-- `invoice_tax_snapshot_full_state_name`. Reference copy.
--
-- Captured by the database (never by an app) the moment an invoice leaves draft,
-- exactly like snapshot_bill_to freezes the billing address. It records what was
-- CHARGED (per line and per distinct rate) and how that compares with the
-- reference rate for the billing address on the invoice's issue date:
--   matches_reference | manual_override | requires_review | no_tax
-- "requires_review" is the safe outcome when the address cannot be resolved or
-- no rate is on file: it never falls back to a rate of zero.
--
-- Invoices generated by a recurring schedule are inserted already sent and get
-- their lines afterwards, so capture waits until lines exist; the totals update
-- that follows (compute_invoice_totals) triggers it.
--
-- The reference rate today comes from public.sales_tax_rates (state-wide rows,
-- source tax_foundation_2026). When ZIP-level or official sources are added,
-- only the lookup inside capture_invoice_tax_snapshot changes; the snapshot
-- shape and everything reading it stay the same.

create table public.invoice_tax_snapshots (
  invoice_id            uuid primary key references public.invoices(id) on delete cascade,
  org_id                uuid not null references public.organizations(id) on delete cascade,
  captured_at           timestamptz not null default now(),
  as_of_date            date not null,
  destination_country   text,
  destination_state     text,
  destination_postal    text,
  status                text not null check (status in ('matches_reference','manual_override','requires_review','no_tax')),
  reason                text,
  reference_rate        numeric(9,4),
  reference_rate_id     uuid,          -- sales_tax_rates.id at the time; no FK on purpose (rows may be replaced)
  reference_jurisdiction text,
  reference_source      text,
  reference_source_url  text,
  reference_effective_from date,
  charged               jsonb not null default '[]'::jsonb,   -- [{rate, taxable_amount, tax_amount}]
  lines                 jsonb not null default '[]'::jsonb,   -- [{sort_order, description, taxable_amount, tax_rate, tax_amount}]
  taxable_total         numeric(18,2) not null default 0,
  tax_total             numeric(18,2) not null default 0,
  currency              text
);
create index invoice_tax_snapshots_org_idx on public.invoice_tax_snapshots (org_id, status);
alter table public.invoice_tax_snapshots enable row level security;
create policy its_select on public.invoice_tax_snapshots for select using (public.is_org_member(org_id) or public.is_super_admin());
grant select on public.invoice_tax_snapshots to authenticated;
grant all on public.invoice_tax_snapshots to service_role;

-- Never updated; deleted only when its invoice is deleted (the cascade runs one
-- trigger level deeper than a direct DELETE).
create or replace function public.trg_invoice_tax_snapshot_immutable() returns trigger
language plpgsql set search_path = public as $$
begin
  if tg_op = 'UPDATE' then
    raise exception 'Invoice tax snapshots cannot be changed' using errcode = 'restrict_violation';
  end if;
  if tg_op = 'DELETE' and pg_trigger_depth() = 1 then
    raise exception 'Invoice tax snapshots cannot be deleted directly' using errcode = 'restrict_violation';
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end $$;
create trigger trg_invoice_tax_snapshot_immutable before update or delete on public.invoice_tax_snapshots
  for each row execute function public.trg_invoice_tax_snapshot_immutable();

create or replace function public.capture_invoice_tax_snapshot(p_invoice_id uuid) returns void
language plpgsql security definer set search_path = public as $$
declare
  inv public.invoices%rowtype;
  v_country text; v_state text; v_zip text; v_code text; v_asof date;
  v_ref public.sales_tax_rates%rowtype; v_has_ref boolean := false;
  v_lines jsonb; v_charged jsonb; v_taxed int; v_mismatch int;
  v_status text; v_reason text; v_taxable numeric(18,2); v_tax numeric(18,2);
begin
  if exists (select 1 from public.invoice_tax_snapshots where invoice_id = p_invoice_id) then return; end if;
  select * into inv from public.invoices where id = p_invoice_id;
  if not found or inv.status = 'draft' then return; end if;
  if not exists (select 1 from public.invoice_items where invoice_id = p_invoice_id) then return; end if;

  v_asof    := coalesce(inv.issue_date, current_date);
  v_country := upper(trim(coalesce(nullif(inv.bill_to_country, ''), 'US')));
  v_state   := upper(trim(coalesce(inv.bill_to_state, '')));
  v_zip     := trim(coalesce(inv.bill_to_postal_code, ''));

  if v_country in ('US', 'USA', 'UNITED STATES') and v_state <> '' then
    if v_state ~ '^[A-Z]{2}$' then v_code := v_state;
    else  -- "Maryland" -> the state-wide row named "Maryland (state rate)"
      select state_code into v_code from public.sales_tax_rates
       where country = 'US' and postal_code is null
         and upper(jurisdiction_name) in (v_state, v_state || ' (STATE RATE)') limit 1;
    end if;
    if v_code is not null then
      select * into v_ref from public.sales_tax_rates
       where country = 'US' and state_code = v_code and category = 'general'
         and effective_from <= v_asof and (effective_to is null or effective_to >= v_asof)
         and (postal_code is null or postal_code = v_zip)
       order by (postal_code is not null) desc, effective_from desc limit 1;
      v_has_ref := found;
    end if;
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
           'sort_order', sort_order, 'description', description,
           'taxable_amount', line_subtotal - line_discount,
           'tax_rate', tax_rate, 'tax_amount', line_tax) order by sort_order), '[]'::jsonb),
         count(*) filter (where tax_rate > 0 or line_tax > 0),
         count(*) filter (where v_has_ref and tax_rate > 0 and round(tax_rate, 4) <> round(v_ref.rate, 4)),
         coalesce(sum(line_subtotal - line_discount) filter (where tax_rate > 0 or line_tax > 0), 0),
         coalesce(sum(line_tax), 0)
    into v_lines, v_taxed, v_mismatch, v_taxable, v_tax
    from public.invoice_items where invoice_id = p_invoice_id;

  select coalesce(jsonb_agg(jsonb_build_object('rate', tax_rate, 'taxable_amount', t, 'tax_amount', x) order by tax_rate), '[]'::jsonb)
    into v_charged
    from (select tax_rate, sum(line_subtotal - line_discount) t, sum(line_tax) x
            from public.invoice_items where invoice_id = p_invoice_id and (tax_rate > 0 or line_tax > 0)
           group by tax_rate) s;

  if v_taxed = 0 then
    v_status := 'no_tax';
  elsif not v_has_ref then
    v_status := 'requires_review';
    v_reason := case
      when v_country not in ('US', 'USA', 'UNITED STATES') then 'Billing address is outside the US: no reference rate'
      when v_state = '' then 'The billing address has no state, so the tax could not be checked'
      when v_code is null then 'The state on the billing address is not recognised'
      else 'No sales-tax rate on file for ' || v_code end;
  elsif v_mismatch = 0 then
    v_status := 'matches_reference';
  else
    v_status := 'manual_override';
    v_reason := 'Rate charged differs from the ' || v_ref.rate || '% reference for ' || v_ref.state_code;
  end if;

  insert into public.invoice_tax_snapshots (
    invoice_id, org_id, as_of_date, destination_country, destination_state, destination_postal,
    status, reason, reference_rate, reference_rate_id, reference_jurisdiction, reference_source,
    reference_source_url, reference_effective_from, charged, lines, taxable_total, tax_total, currency)
  values (
    inv.id, inv.org_id, v_asof, v_country, coalesce(v_code, nullif(v_state, '')), nullif(v_zip, ''),
    v_status, v_reason,
    case when v_has_ref then v_ref.rate end, case when v_has_ref then v_ref.id end,
    case when v_has_ref then v_ref.jurisdiction_name end, case when v_has_ref then v_ref.source end,
    case when v_has_ref then v_ref.source_url end, case when v_has_ref then v_ref.effective_from end,
    v_charged, v_lines, v_taxable, v_tax, inv.currency)
  on conflict (invoice_id) do nothing;
end $$;
revoke all on function public.capture_invoice_tax_snapshot(uuid) from public, anon, authenticated;
grant execute on function public.capture_invoice_tax_snapshot(uuid) to service_role;

create or replace function public.trg_capture_invoice_tax_snapshot() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  perform public.capture_invoice_tax_snapshot(new.id);
  return null;
end $$;
create trigger trg_capture_invoice_tax_snapshot after insert or update on public.invoices
  for each row when (new.status <> 'draft') execute function public.trg_capture_invoice_tax_snapshot();

-- ── 2026-09-26: tax-exempt clients (migration `clients_tax_exempt_and_snapshot_rule`) ──
-- QuickBooks/Xero pattern: a customer can be marked exempt (with a reason). The
-- apps skip auto-tax for them, and the snapshot flags an issued invoice that
-- charged tax to an exempt client as requires_review:
--   alter table public.clients
--     add column if not exists tax_exempt boolean not null default false,
--     add column if not exists tax_exempt_reason text;
-- and inside capture_invoice_tax_snapshot, after computing v_taxed:
--   select coalesce(tax_exempt,false) into v_exempt from public.clients where id = inv.client_id;
--   ... elsif v_exempt then v_status := 'requires_review';
--       v_reason := 'The client is marked tax-exempt, but sales tax was charged';
